export const catalogLanguageCodes = ["en", "de", "ru", "tr", "uz"] as const;

export type CatalogLanguageCode = (typeof catalogLanguageCodes)[number];

export type LocalizedCatalogNames = Record<CatalogLanguageCode, string>;

export const localizedCategoryNames: Record<string, LocalizedCatalogNames> = {
  AM: {
    en: "Mopeds and light quadricycles",
    de: "Mopeds und leichte vierrädrige Fahrzeuge",
    ru: "Мопеды и лёгкие квадрициклы",
    tr: "Mopedler ve hafif dört tekerlekli araçlar",
    uz: "Mopedlar va yengil kvadrosikllar",
  },
  A1: {
    en: "Light motorcycles",
    de: "Leichtkrafträder",
    ru: "Лёгкие мотоциклы",
    tr: "Hafif motosikletler",
    uz: "Yengil mototsikllar",
  },
  A2: {
    en: "Medium motorcycles",
    de: "Motorräder der Klasse A2",
    ru: "Средние мотоциклы",
    tr: "Orta sınıf motosikletler",
    uz: "O‘rta toifadagi mototsikllar",
  },
  A: {
    en: "Motorcycles",
    de: "Motorräder",
    ru: "Мотоциклы",
    tr: "Motosikletler",
    uz: "Mototsikllar",
  },
  B: {
    en: "Passenger cars",
    de: "Pkw",
    ru: "Легковые автомобили",
    tr: "Binek otomobiller",
    uz: "Yengil avtomobillar",
  },
  BF17: {
    en: "Accompanied driving from 17",
    de: "Begleitetes Fahren ab 17",
    ru: "Сопровождаемое вождение с 17 лет",
    tr: "17 yaşından itibaren eşli sürüş",
    uz: "17 yoshdan boshlab kuzatuvli haydash",
  },
  B197: {
    en: "Category B with automatic test",
    de: "Klasse B mit Automatik-Prüfung",
    ru: "Категория B с автоматическим экзаменом",
    tr: "Otomatik sınavlı B kategorisi",
    uz: "Avtomatik imtihonli B toifasi",
  },
  B96: {
    en: "Car and trailer combination",
    de: "Pkw-Anhänger-Gespann",
    ru: "Легковой автомобиль с прицепом",
    tr: "Otomobil ve römork kombinasyonu",
    uz: "Yengil avtomobil va tirkama majmuasi",
  },
  BE: {
    en: "Passenger car with trailer",
    de: "Pkw mit Anhänger",
    ru: "Легковой автомобиль с прицепом",
    tr: "Römorklu binek otomobil",
    uz: "Tirkamali yengil avtomobil",
  },
  C1: {
    en: "Medium goods vehicles",
    de: "Leichte Lkw",
    ru: "Средние грузовые автомобили",
    tr: "Orta sınıf yük araçları",
    uz: "O‘rta yuk avtomobillari",
  },
  C1E: {
    en: "Medium goods vehicle combinations",
    de: "Leichte Lkw mit Anhänger",
    ru: "Сочленения грузовых автомобилей среднего класса",
    tr: "Orta sınıf yük aracı kombinasyonları",
    uz: "O‘rta yuk avtomobili va tirkama",
  },
  C: {
    en: "Heavy goods vehicles",
    de: "Lkw",
    ru: "Тяжёлые грузовые автомобили",
    tr: "Ağır yük araçları",
    uz: "Og‘ir yuk avtomobillari",
  },
  CE: {
    en: "Heavy goods vehicle combinations",
    de: "Lkw mit Anhänger",
    ru: "Тяжёлые грузовые автопоезда",
    tr: "Ağır yük aracı kombinasyonları",
    uz: "Og‘ir yuk avtomobili va tirkama",
  },
  D1: {
    en: "Minibuses",
    de: "Kleinbusse",
    ru: "Микроавтобусы",
    tr: "Minibüsler",
    uz: "Mikroavtobuslar",
  },
  D1E: {
    en: "Minibus combinations",
    de: "Kleinbusse mit Anhänger",
    ru: "Комбинации микроавтобусов",
    tr: "Minibüs kombinasyonları",
    uz: "Mikroavtobus va tirkama majmuasi",
  },
  D: {
    en: "Buses",
    de: "Busse",
    ru: "Автобусы",
    tr: "Otobüsler",
    uz: "Avtobuslar",
  },
  DE: {
    en: "Bus combinations",
    de: "Busse mit Anhänger",
    ru: "Автобусные автопоезда",
    tr: "Otobüs kombinasyonları",
    uz: "Avtobus va tirkama majmuasi",
  },
  L: {
    en: "Agricultural tractors",
    de: "Landwirtschaftliche Zugmaschinen",
    ru: "Сельскохозяйственные тракторы",
    tr: "Tarım traktörleri",
    uz: "Qishloq xo‘jaligi traktorlari",
  },
  T: {
    en: "High-speed agricultural tractors",
    de: "Schnelle landwirtschaftliche Zugmaschinen",
    ru: "Быстрые сельскохозяйственные тракторы",
    tr: "Hızlı tarım traktörleri",
    uz: "Tezkor qishloq xo‘jaligi traktorlari",
  },
};

export const localizedGenericTopicNames: Record<string, LocalizedCatalogNames> = {
  mixed: {
    en: "Mixed",
    de: "Gemischt",
    ru: "Смешанная",
    tr: "Karışık",
    uz: "Aralash",
  },
  "traffic-signs": {
    en: "Traffic Signs",
    de: "Verkehrszeichen",
    ru: "Дорожные знаки",
    tr: "Trafik işaretleri",
    uz: "Yo‘l belgilari",
  },
  "right-of-way": {
    en: "Right of Way",
    de: "Vorfahrt",
    ru: "Приоритет проезда",
    tr: "Geçiş üstünlüğü",
    uz: "Yo‘l ustunligi",
  },
  speed: {
    en: "Speed",
    de: "Geschwindigkeit",
    ru: "Скорость",
    tr: "Hız",
    uz: "Tezlik",
  },
  distance: {
    en: "Distance",
    de: "Abstand",
    ru: "Дистанция",
    tr: "Mesafe",
    uz: "Masofa",
  },
  overtaking: {
    en: "Overtaking",
    de: "Überholen",
    ru: "Обгон",
    tr: "Sollama",
    uz: "Quvib o‘tish",
  },
  "parking-and-stopping": {
    en: "Parking and Stopping",
    de: "Halten und Parken",
    ru: "Остановка и стоянка",
    tr: "Durma ve park etme",
    uz: "To‘xtash va park qilish",
  },
  "turning-and-intersections": {
    en: "Turning and Intersections",
    de: "Abbiegen und Kreuzungen",
    ru: "Повороты и перекрёстки",
    tr: "Dönüşler ve kavşaklar",
    uz: "Burilishlar va chorrahalar",
  },
  "alcohol-and-drugs": {
    en: "Alcohol and Drugs",
    de: "Alkohol und Drogen",
    ru: "Алкоголь и наркотики",
    tr: "Alkol ve uyuşturucu",
    uz: "Alkogol va giyohvand moddalar",
  },
  environment: {
    en: "Environment",
    de: "Umwelt",
    ru: "Окружающая среда",
    tr: "Çevre",
    uz: "Atrof-muhit",
  },
  "technical-knowledge": {
    en: "Technical Knowledge",
    de: "Technisches Wissen",
    ru: "Технические знания",
    tr: "Teknik bilgi",
    uz: "Texnik bilimlar",
  },
  "hazard-awareness": {
    en: "Hazard Awareness",
    de: "Gefahrenwahrnehmung",
    ru: "Осознание опасности",
    tr: "Tehlike farkındalığı",
    uz: "Xavfni anglash",
  },
  "emergency-behavior": {
    en: "Emergency Behavior",
    de: "Verhalten in Notfällen",
    ru: "Поведение в чрезвычайных ситуациях",
    tr: "Acil durum davranışı",
    uz: "Favqulodda vaziyatdagi xulq-atvor",
  },
  trailer: {
    en: "Trailer",
    de: "Anhänger",
    ru: "Прицеп",
    tr: "Römork",
    uz: "Tirkama",
  },
  truck: {
    en: "Truck",
    de: "Lkw",
    ru: "Грузовик",
    tr: "Kamyon",
    uz: "Yuk mashinasi",
  },
  bus: {
    en: "Bus",
    de: "Bus",
    ru: "Автобус",
    tr: "Otobüs",
    uz: "Avtobus",
  },
  motorcycle: {
    en: "Motorcycle",
    de: "Motorrad",
    ru: "Мотоцикл",
    tr: "Motosiklet",
    uz: "Mototsikl",
  },
  "agricultural-vehicles": {
    en: "Agricultural Vehicles",
    de: "Landwirtschaftliche Fahrzeuge",
    ru: "Сельскохозяйственные машины",
    tr: "Tarım araçları",
    uz: "Qishloq xo‘jaligi transport vositalari",
  },
  "road-signs": {
    en: "Road Signs",
    de: "Straßenzeichen",
    ru: "Дорожные знаки",
    tr: "Yol işaretleri",
    uz: "Yo‘l belgilar",
  },
  "safe-driving": {
    en: "Safe Driving",
    de: "Sicheres Fahren",
    ru: "Безопасное вождение",
    tr: "Güvenli sürüş",
    uz: "Xavfsiz haydash",
  },
  "vehicle-technology": {
    en: "Vehicle Technology",
    de: "Fahrzeugtechnik",
    ru: "Техника автомобиля",
    tr: "Araç teknolojisi",
    uz: "Transport vositasi texnologiyasi",
  },
  "professional-driving": {
    en: "Professional and Heavy Vehicles",
    de: "Berufskraftverkehr und schwere Fahrzeuge",
    ru: "Профессиональное вождение и тяжёлые автомобили",
    tr: "Profesyonel ve ağır araçlar",
    uz: "Kasbiy va og‘ir transport vositalari",
  },
};

export function getLocalizedCategoryName(code: string, language: CatalogLanguageCode) {
  return localizedCategoryNames[code]?.[language] ?? localizedCategoryNames[code]?.en ?? code;
}

export function getLocalizedGenericTopicName(slug: string, language: CatalogLanguageCode) {
  return localizedGenericTopicNames[slug]?.[language] ?? localizedGenericTopicNames[slug]?.en ?? slug;
}

function normalizeLabel(value: string) {
  return value
    .replace(/\s+/g, " ")
    .trim();
}

function applyReplacements(value: string, replacements: Array<[RegExp, string]>) {
  let result = value;
  for (const [pattern, replacement] of replacements) {
    result = result.replace(pattern, replacement);
  }
  return normalizeLabel(result);
}

const importedTopicReplacements: Record<Exclude<CatalogLanguageCode, "en" | "de">, Array<[RegExp, string]>> = {
  ru: [
    [/Basic Forms Of Traffic Behaviour/gi, "Основные формы поведения в дорожном движении"],
    [/Basic Forms Of Traffic Behavior/gi, "Основные формы поведения в дорожном движении"],
    [/Behaviour Towards Pedestrians/gi, "Поведение по отношению к пешеходам"],
    [/Behavior Towards Pedestrians/gi, "Поведение по отношению к пешеходам"],
    [/Road And Weather Conditions/gi, "Дорожные и погодные условия"],
    [/Darkness And Poor Visibility/gi, "Темнота и плохая видимость"],
    [/Special Traffic Situations/gi, "Особые дорожные ситуации"],
    [/Alcohol Drugs Medication/gi, "Алкоголь, наркотики, лекарства"],
    [/Health Risks/gi, "Риски для здоровья"],
    [/Basic Rules About Behaviour In Road Traffic/gi, "Основные правила поведения в дорожном движении"],
    [/Basic Rules About Behavior In Road Traffic/gi, "Основные правила поведения в дорожном движении"],
    [/Road Use/gi, "Использование дорог"],
    [/Distance/gi, "Дистанция"],
    [/Passing/gi, "Объезд"],
    [/Use Of Lanes By Motor Vehicles/gi, "Использование полос движения автотранспортом"],
    [/Turning Turning And Reversing/gi, "Поворот, разворот и движение задним ходом"],
    [/Entering And Starting/gi, "Въезд и начало движения"],
    [/Stopping And Parking/gi, "Остановка и стоянка"],
    [/Warning Signs/gi, "Предупреждающие знаки"],
    [/Lighting/gi, "Освещение"],
    [/Level Crossings/gi, "Железнодорожные переезды"],
    [/Public Transport And School Buses/gi, "Общественный транспорт и школьные автобусы"],
    [/Load/gi, "Груз"],
    [/Other Duties Of The Driver/gi, "Другие обязанности водителя"],
    [/Behaviour At Pedestrian Crossings And Towards Pedestrians/gi, "Поведение на пешеходных переходах и по отношению к пешеходам"],
    [/Behavior At Pedestrian Crossings And Towards Pedestrians/gi, "Поведение на пешеходных переходах и по отношению к пешеходам"],
    [/Accident/gi, "Авария"],
    [/Signs And Instructions From Police Officers/gi, "Сигналы и указания сотрудников полиции"],
    [/Variable And Steady Light Signals/gi, "Переменные и постоянные световые сигналы"],
    [/Blue Flashing Light And Yellow Flashing Light/gi, "Синий проблесковый маячок и жёлтый проблесковый маячок"],
    [/Priority/gi, "Приоритет"],
    [/Danger Sign/gi, "Знак опасности"],
    [/Regulatory Sign/gi, "Предписывающий знак"],
    [/Directional Sign/gi, "Указательный знак"],
    [/Traffic Facilities/gi, "Дорожные устройства"],
    [/Environmental Protection/gi, "Защита окружающей среды"],
    [/Driving Operation Driving Physics Driving Technique/gi, "Управление, физика движения и техника вождения"],
    [/Qualification And Ability Of Drivers/gi, "Квалификация и пригодность водителей"],
    [/Motorway/gi, "Автомагистраль"],
    [/Fatigue Distraction/gi, "Усталость и отвлечение"],
    [/Affective Emotional Behaviour In Road Traffic/gi, "Эмоционально-аффективное поведение в дорожном движении"],
    [/Affective Emotional Behavior In Road Traffic/gi, "Эмоционально-аффективное поведение в дорожном движении"],
    [/Parking Time Monitoring Devices/gi, "Устройства контроля времени парковки"],
    [/Duty Of Care/gi, "Обязанность заботы"],
    [/Immobilisation And Towing Of Vehicles/gi, "Обездвиживание и буксировка транспортных средств"],
    [/Passenger Transport/gi, "Перевозка пассажиров"],
    [/Excessive Road Use/gi, "Чрезмерное использование дороги"],
    [/Sunday Driving Ban/gi, "Запрет на воскресное вождение"],
    [/Traffic Obstructions/gi, "Помехи движению"],
    [/Vehicles With Right Of Way/gi, "Транспортные средства с преимущественным правом проезда"],
    [/Examination Of The Vehicles/gi, "Осмотр транспортных средств"],
    [/Admission To Road Traffic Vehicle Documents Driving Licence/gi, "Допуск к дорожному движению, документы на транспортное средство и водительское удостоверение"],
    [/Trailer Operation/gi, "Эксплуатация прицепа"],
    [/Driving And Rest Periods/gi, "Время вождения и отдыха"],
    [/Ec Monitoring Device/gi, "Контрольное устройство ЕС"],
    [/Dimensions Weights And Speed Limiters/gi, "Габариты, массы и ограничители скорости"],
    [/Reading A Road Map And Route Planning/gi, "Чтение дорожной карты и планирование маршрута"],
    [/Fault Detection Localisation Of Faults/gi, "Обнаружение неисправностей и локализация неисправностей"],
    [/Combustion Engine Fluids Fuel System Electrical System Ignition Power Transmission/gi, "Двигатель внутреннего сгорания, жидкости, топливная система, электрическая система, зажигание и передача мощности"],
    [/Lubricants And Antifreeze/gi, "Смазочные материалы и антифриз"],
    [/Use And Maintenance Of Tyres/gi, "Использование и обслуживание шин"],
    [/Brake Systems And Cruise Control/gi, "Тормозные системы и круиз-контроль"],
    [/Trailer Coupling Systems/gi, "Системы сцепки прицепа"],
    [/Maintenance Of Motor Vehicles And Timely Arrangement Of Repairs/gi, "Техническое обслуживание автомобилей и своевременное проведение ремонтов"],
    [/Receipt Transport And Delivery Of Goods/gi, "Приёмка, перевозка и доставка грузов"],
    [/Equipment Of Vehicles/gi, "Оснащение транспортных средств"],
    [/Qualification And Ability Of Truck Drivers/gi, "Квалификация и пригодность водителей грузовиков"],
  ],
  tr: [
    [/Basic Forms Of Traffic Behaviour/gi, "Trafik davranışının temel biçimleri"],
    [/Basic Forms Of Traffic Behavior/gi, "Trafik davranışının temel biçimleri"],
    [/Behaviour Towards Pedestrians/gi, "Yayalara karşı davranış"],
    [/Behavior Towards Pedestrians/gi, "Yayalara karşı davranış"],
    [/Road And Weather Conditions/gi, "Yol ve hava koşulları"],
    [/Darkness And Poor Visibility/gi, "Karanlık ve düşük görüş"],
    [/Special Traffic Situations/gi, "Özel trafik durumları"],
    [/Alcohol Drugs Medication/gi, "Alkol, uyuşturucu, ilaçlar"],
    [/Health Risks/gi, "Sağlık riskleri"],
    [/Basic Rules About Behaviour In Road Traffic/gi, "Karayolu trafiğinde davranışın temel kuralları"],
    [/Basic Rules About Behavior In Road Traffic/gi, "Karayolu trafiğinde davranışın temel kuralları"],
    [/Road Use/gi, "Yol kullanımı"],
    [/Distance/gi, "Mesafe"],
    [/Passing/gi, "Geçip gitme"],
    [/Use Of Lanes By Motor Vehicles/gi, "Motorlu araçların şerit kullanımı"],
    [/Turning Turning And Reversing/gi, "Dönüş, U dönüşü ve geri manevra"],
    [/Entering And Starting/gi, "Yola girme ve hareket etme"],
    [/Stopping And Parking/gi, "Durma ve park etme"],
    [/Warning Signs/gi, "Uyarı işaretleri"],
    [/Lighting/gi, "Aydınlatma"],
    [/Level Crossings/gi, "Hemzemin geçitler"],
    [/Public Transport And School Buses/gi, "Toplu taşıma ve okul otobüsleri"],
    [/Load/gi, "Yük"],
    [/Other Duties Of The Driver/gi, "Sürücünün diğer görevleri"],
    [/Behaviour At Pedestrian Crossings And Towards Pedestrians/gi, "Yaya geçitlerinde ve yayalara karşı davranış"],
    [/Behavior At Pedestrian Crossings And Towards Pedestrians/gi, "Yaya geçitlerinde ve yayalara karşı davranış"],
    [/Accident/gi, "Kaza"],
    [/Signs And Instructions From Police Officers/gi, "Polis memurlarının işaret ve talimatları"],
    [/Variable And Steady Light Signals/gi, "Değişken ve sabit ışık sinyalleri"],
    [/Blue Flashing Light And Yellow Flashing Light/gi, "Mavi yanıp sönen ışık ve sarı yanıp sönen ışık"],
    [/Priority/gi, "Geçiş önceliği"],
    [/Danger Sign/gi, "Tehlike işareti"],
    [/Regulatory Sign/gi, "Düzenleyici işaret"],
    [/Directional Sign/gi, "Yönlendirici işaret"],
    [/Traffic Facilities/gi, "Trafik tesisleri"],
    [/Environmental Protection/gi, "Çevre koruma"],
    [/Driving Operation Driving Physics Driving Technique/gi, "Sürüş işletimi, sürüş fiziği ve sürüş tekniği"],
    [/Qualification And Ability Of Drivers/gi, "Sürücülerin yeterliliği ve ehliyeti"],
    [/Motorway/gi, "Otoyol"],
    [/Fatigue Distraction/gi, "Yorgunluk ve dikkat dağınıklığı"],
    [/Affective Emotional Behaviour In Road Traffic/gi, "Trafikte duygusal davranış"],
    [/Affective Emotional Behavior In Road Traffic/gi, "Trafikte duygusal davranış"],
    [/Parking Time Monitoring Devices/gi, "Park süresi izleme cihazları"],
    [/Duty Of Care/gi, "Özen yükümlülüğü"],
    [/Immobilisation And Towing Of Vehicles/gi, "Araçların hareketsizleştirilmesi ve çekilmesi"],
    [/Passenger Transport/gi, "Yolcu taşımacılığı"],
    [/Excessive Road Use/gi, "Aşırı yol kullanımı"],
    [/Sunday Driving Ban/gi, "Pazar günü sürüş yasağı"],
    [/Traffic Obstructions/gi, "Trafik engelleri"],
    [/Vehicles With Right Of Way/gi, "Geçiş önceliği olan araçlar"],
    [/Examination Of The Vehicles/gi, "Araçların muayenesi"],
    [/Admission To Road Traffic Vehicle Documents Driving Licence/gi, "Karayolu trafiğine kabul, araç belgeleri ve sürücü belgesi"],
    [/Trailer Operation/gi, "Römork kullanımı"],
    [/Driving And Rest Periods/gi, "Sürüş ve dinlenme süreleri"],
    [/Ec Monitoring Device/gi, "Kontrol cihazı"],
    [/Dimensions Weights And Speed Limiters/gi, "Boyutlar, ağırlıklar ve hız sınırlayıcılar"],
    [/Reading A Road Map And Route Planning/gi, "Yol haritasını okuma ve rota planlama"],
    [/Fault Detection Localisation Of Faults/gi, "Arıza tespiti ve arızanın yeri"],
    [/Combustion Engine Fluids Fuel System Electrical System Ignition Power Transmission/gi, "İçten yanmalı motor, sıvılar, yakıt sistemi, elektrik sistemi, ateşleme ve güç aktarımı"],
    [/Lubricants And Antifreeze/gi, "Yağlayıcılar ve antifriz"],
    [/Use And Maintenance Of Tyres/gi, "Lastiklerin kullanımı ve bakımı"],
    [/Brake Systems And Cruise Control/gi, "Fren sistemleri ve hız sabitleyici"],
    [/Trailer Coupling Systems/gi, "Römork bağlantı sistemleri"],
    [/Maintenance Of Motor Vehicles And Timely Arrangement Of Repairs/gi, "Motorlu araçların bakımı ve onarımların zamanında yaptırılması"],
    [/Receipt Transport And Delivery Of Goods/gi, "Malların teslim alınması, taşınması ve teslimi"],
    [/Equipment Of Vehicles/gi, "Araç donanımı"],
    [/Qualification And Ability Of Truck Drivers/gi, "Kamyon sürücülerinin yeterliliği ve ehliyeti"],
  ],
  uz: [
    [/Basic Forms Of Traffic Behaviour/gi, "Yo‘l harakatidagi xulq-atvorning asosiy shakllari"],
    [/Basic Forms Of Traffic Behavior/gi, "Yo‘l harakatidagi xulq-atvorning asosiy shakllari"],
    [/Behaviour Towards Pedestrians/gi, "Piyodalarga nisbatan xulq-atvor"],
    [/Behavior Towards Pedestrians/gi, "Piyodalarga nisbatan xulq-atvor"],
    [/Road And Weather Conditions/gi, "Yo‘l va ob-havo sharoitlari"],
    [/Darkness And Poor Visibility/gi, "Qorong‘ulik va yomon ko‘rinish"],
    [/Special Traffic Situations/gi, "Maxsus yo‘l harakati holatlari"],
    [/Alcohol Drugs Medication/gi, "Alkogol, giyohvand moddalar, dorilar"],
    [/Health Risks/gi, "Sog‘liq uchun xavflar"],
    [/Basic Rules About Behaviour In Road Traffic/gi, "Yo‘l harakatidagi xulq-atvorning asosiy qoidalari"],
    [/Basic Rules About Behavior In Road Traffic/gi, "Yo‘l harakatidagi xulq-atvorning asosiy qoidalari"],
    [/Road Use/gi, "Yo‘ldan foydalanish"],
    [/Distance/gi, "Masofa"],
    [/Passing/gi, "Yonidan o‘tish"],
    [/Use Of Lanes By Motor Vehicles/gi, "Motorli transport vositalarining bo‘laklardan foydalanishi"],
    [/Turning Turning And Reversing/gi, "Burilish, qayrilish va orqaga harakatlanish"],
    [/Entering And Starting/gi, "Yo‘lga kirish va harakatni boshlash"],
    [/Stopping And Parking/gi, "To‘xtash va park qilish"],
    [/Warning Signs/gi, "Ogohlantiruvchi belgilar"],
    [/Lighting/gi, "Yoritish"],
    [/Level Crossings/gi, "Temir yo‘l kesishmalari"],
    [/Public Transport And School Buses/gi, "Jamoat transporti va maktab avtobuslari"],
    [/Load/gi, "Yuk"],
    [/Other Duties Of The Driver/gi, "Haydovchining boshqa vazifalari"],
    [/Behaviour At Pedestrian Crossings And Towards Pedestrians/gi, "Piyodalar o‘tish joylarida va piyodalarga nisbatan xulq-atvor"],
    [/Behavior At Pedestrian Crossings And Towards Pedestrians/gi, "Piyodalar o‘tish joylarida va piyodalarga nisbatan xulq-atvor"],
    [/Accident/gi, "YTH"],
    [/Signs And Instructions From Police Officers/gi, "Politsiya xodimlarining ishoralari va ko‘rsatmalari"],
    [/Variable And Steady Light Signals/gi, "O‘zgaruvchan va doimiy yorug‘lik signallari"],
    [/Blue Flashing Light And Yellow Flashing Light/gi, "Ko‘k chaqnab yonuvchi chiroq va sariq chaqnab yonuvchi chiroq"],
    [/Priority/gi, "Yo‘l ustunligi"],
    [/Danger Sign/gi, "Xavf belgisi"],
    [/Regulatory Sign/gi, "Majburiy belgi"],
    [/Directional Sign/gi, "Yo‘naltiruvchi belgi"],
    [/Traffic Facilities/gi, "Yo‘l inshootlari"],
    [/Environmental Protection/gi, "Atrof-muhitni muhofaza qilish"],
    [/Driving Operation Driving Physics Driving Technique/gi, "Avtomobilni boshqarish, harakat fizikasi va haydash texnikasi"],
    [/Qualification And Ability Of Drivers/gi, "Haydovchilarning malakasi va layoqati"],
    [/Motorway/gi, "Avtomagistral"],
    [/Fatigue Distraction/gi, "Charchoq va chalg‘ish"],
    [/Affective Emotional Behaviour In Road Traffic/gi, "Yo‘l harakatidagi affektiv-emotsional xulq-atvor"],
    [/Affective Emotional Behavior In Road Traffic/gi, "Yo‘l harakatidagi affektiv-emotsional xulq-atvor"],
    [/Parking Time Monitoring Devices/gi, "Park vaqtini nazorat qilish qurilmalari"],
    [/Duty Of Care/gi, "Ehtiyotkorlik burchi"],
    [/Immobilisation And Towing Of Vehicles/gi, "Transport vositalarini harakatsizlantirish va tortib olib ketish"],
    [/Passenger Transport/gi, "Yo‘lovchi tashish"],
    [/Excessive Road Use/gi, "Yo‘ldan ortiqcha foydalanish"],
    [/Sunday Driving Ban/gi, "Yakshanba kuni haydash taqiqi"],
    [/Traffic Obstructions/gi, "Yo‘l harakati to‘siqlari"],
    [/Vehicles With Right Of Way/gi, "Ustunlik huquqiga ega transport vositalari"],
    [/Examination Of The Vehicles/gi, "Transport vositalarini tekshirish"],
    [/Admission To Road Traffic Vehicle Documents Driving Licence/gi, "Yo‘l harakatiga ruxsat, transport hujjatlari va haydovchilik guvohnomasi"],
    [/Trailer Operation/gi, "Tirkama ishlatish"],
    [/Driving And Rest Periods/gi, "Haydash va dam olish vaqtlari"],
    [/Ec Monitoring Device/gi, "Nazorat qurilmasi"],
    [/Dimensions Weights And Speed Limiters/gi, "O‘lchamlar, og‘irliklar va tezlik cheklagichlar"],
    [/Reading A Road Map And Route Planning/gi, "Yo‘l xaritasini o‘qish va marshrutni rejalashtirish"],
    [/Fault Detection Localisation Of Faults/gi, "Nosozliklarni aniqlash va lokalizatsiya qilish"],
    [/Combustion Engine Fluids Fuel System Electrical System Ignition Power Transmission/gi, "Ichki yonuv dvigateli, suyuqliklar, yonilg‘i tizimi, elektr tizimi, yoqish va quvvat uzatish"],
    [/Lubricants And Antifreeze/gi, "Moylash materiallari va antifriz"],
    [/Use And Maintenance Of Tyres/gi, "Shinalardan foydalanish va ularga xizmat ko‘rsatish"],
    [/Brake Systems And Cruise Control/gi, "Tormoz tizimlari va kruiz-kontrol"],
    [/Trailer Coupling Systems/gi, "Tirkama ulash tizimlari"],
    [/Maintenance Of Motor Vehicles And Timely Arrangement Of Repairs/gi, "Avtotransport vositalariga texnik xizmat ko‘rsatish va ta’mirlarni o‘z vaqtida tashkil etish"],
    [/Receipt Transport And Delivery Of Goods/gi, "Yuklarni qabul qilish, tashish va yetkazib berish"],
    [/Equipment Of Vehicles/gi, "Transport vositalarining jihozlanishi"],
    [/Qualification And Ability Of Truck Drivers/gi, "Yuk mashinasi haydovchilarining malakasi va layoqati"],
  ],
};

export function translateImportedTopicName(name: string, language: Exclude<CatalogLanguageCode, "en" | "de">) {
  return applyReplacements(name, importedTopicReplacements[language]);
}

export function localizedImportedTopicNames(enName: string, deName?: string | null): LocalizedCatalogNames {
  return {
    en: normalizeLabel(enName),
    de: normalizeLabel(deName ?? enName),
    ru: translateImportedTopicName(enName, "ru"),
    tr: translateImportedTopicName(enName, "tr"),
    uz: translateImportedTopicName(enName, "uz"),
  };
}

